name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 1.20.1-forge-47.3.3
    paths:
      - src/*
      - gradle/*
      - .github/workflows/*
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Gradle version
        run: gradle wrapper --gradle-version 7.6.4

      - name: Test Server
        run: gradle runGameTestServer

      - name: Build
        run: gradle build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: 1.20.1-Below-Create-6.0.0-Forge