name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 1.20.1-6.0.0-forge
    paths:
      - src/*
      - gradle/*
      - .github/workflows/*
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Build with Gradle
        run: gradle build

      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: 1.20.1-6.0.0-Forge_NeoForge-${{ steps.create_timestamp.outputs.timestamp }}
          github-draft: false
          github-prerelease: true

      - uses: actions/upload-artifact@v4
        with:
          name: Build Artifact
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
            build/libs
          retention-days: 1
        if: always()
  GameTest:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        GameTestConfig: [ default, testAE ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Test Server with ${{ matrix.GameTestConfig }}
        run: gradle runGameTestServer -PGameTestConfig=${{ matrix.GameTestConfig }}
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Test Artifact of ${{ matrix.GameTestConfig }}
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
            build/libs
          retention-days: 7
        if: always()