name: test.yml
on:
  workflow_dispatch:
  pull_request:
jobs:
  GameTest:
    strategy:
      matrix:
        GameTestConfig: [ default, testAE ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Test Server with ${{ matrix.GameTestConfig }}
        run: gradle runGameTestServer -PGameTestConfig=${{ matrix.GameTestConfig }} -Dforge.enabledGameTestNamespaces=smartercontraptionstorage

      - uses: actions/upload-artifact@v4
        with:
          name: Test Artifact of ${{ matrix.GameTestConfig }}
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
          retention-days: 7
        if: always()
